title: Vanilla OS Handbook
author: Vanilla OS Contributors
email: send@mirko.pm

assets: /assets
uploads: /uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed