title: Vanilla OS Handbook
author: Vanilla OS Contributors
email: send@mirko.pm

assets: /assets
uploads: /uploads

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

url: https://handbook.vanillaos.org
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
